#!/usr/bin/env python3

import rospy
import open3d as o3d
import rasterio
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import os

# ================= CONFIGURATION =================
COLORMAP = cm.gray      # gray, viridis, inferno, etc.
NODATA_VALUE = 0

def wait_for_files(mesh_file, sss_tif):
    """
    Waits until both the mesh file and the SSS geotiff exist.
    """
    rospy.loginfo("Fusion node initialized. Waiting for input files to be generated...")
    rate = rospy.Rate(0.5)  # Check every 2 seconds (0.5 Hz)
    
    while not rospy.is_shutdown():
        mesh_exists = os.path.isfile(mesh_file)
        sss_exists = os.path.isfile(sss_tif)
        
        if mesh_exists and sss_exists:
            rospy.loginfo("✔ Both input files found!")
            # Wait an extra 2 seconds to ensure the other nodes have completely 
            # finished writing and closed the files to avoid read errors.
            rospy.sleep(2.0) 
            return True
        else:
            # Print a waiting message every 10 seconds to avoid spamming the terminal
            missing = []
            if not mesh_exists: missing.append("Mesh (.ply)")
            if not sss_exists: missing.append("SSS Mosaic (.tif)")
            rospy.loginfo_throttle(10.0, f"Still waiting for: {', '.join(missing)}...")
            
            rate.sleep()
            
    return False # Returns False if ROS is shut down (Ctrl+C) before files are found

def main():
    # INITIALIZE ROS NODE
    rospy.init_node('fusion_node', anonymous=True)

    # READ PARAMETERS FROM THE LAUNCH FILE
    mesh_file  = rospy.get_param('~mesh_file', '')
    sss_tif    = rospy.get_param('~sss_tif', '')
    output_dir = rospy.get_param('~output_dir', '.')

    if not mesh_file or not sss_tif:
        rospy.logerr("ERROR: 'mesh_file' or 'sss_tif' not provided. Aborting.")
        return

    # CREATE THE OUTPUT FILE PATH
    output_mesh = os.path.join(output_dir, "mb_textured_sss.ply")

    # ================= WAIT FOR FILES =================
    # The script will pause here until files are generated by the other nodes
    if not wait_for_files(mesh_file, sss_tif):
        rospy.logwarn("Fusion node stopped before files were found.")
        return

    # -----------------------------
    # 1. LOAD MB MESH
    # -----------------------------
    rospy.loginfo(f"Loading MB mesh from: {mesh_file}")
    mesh = o3d.io.read_triangle_mesh(mesh_file)
    mesh.compute_vertex_normals()

    vertices = np.asarray(mesh.vertices)
    rospy.loginfo(f"Vertices loaded: {len(vertices)}")

    if len(vertices) == 0:
        rospy.logerr("ERROR: The loaded mesh has 0 vertices.")
        return

    # -----------------------------
    # 2. LOAD SSS MOSAIC
    # -----------------------------
    rospy.loginfo(f"Loading SSS mosaic from: {sss_tif}")
    try:
        with rasterio.open(sss_tif) as src:
            sss = src.read(1)
            nodata = src.nodata
            
            def get_pixel_value(x, y):
                try:
                    row, col = src.index(x, y)
                    if 0 <= row < sss.shape[0] and 0 <= col < sss.shape[1]:
                        val = sss[row, col]
                        if nodata is not None and val == nodata:
                            return NODATA_VALUE
                        return val
                    return NODATA_VALUE
                except Exception:
                    return NODATA_VALUE
                    
            # -----------------------------
            # 3. PROJECT SSS → VERTICES
            # -----------------------------
            rospy.loginfo("Projecting SSS intensity onto the mesh...")
            intensity = np.zeros(len(vertices), dtype=np.float32)

            for i, (x, y, z) in enumerate(vertices):
                intensity[i] = get_pixel_value(x, y)

    except Exception as e:
        rospy.logerr(f"Failed to read SSS GeoTIFF: {e}")
        return

    # -----------------------------
    # 4. NORMALIZE + COLOR MAP
    # -----------------------------
    rospy.loginfo("Normalizing intensity and applying colormap...")

    valid = intensity > NODATA_VALUE
    rospy.loginfo(f"Vertices with valid intensity: {np.sum(valid)} / {len(valid)}")

    if not np.any(valid):
        rospy.logerr(
            "ERROR: No mesh vertices intersect with the SSS mosaic. "
            "Check the CRS, coordinate systems, and spatial overlap."
        )
        return

    imin, imax = intensity[valid].min(), intensity[valid].max()
    
    denominator = (imax - imin) if (imax - imin) > 0 else 1.0
    int_norm = np.zeros_like(intensity)
    int_norm[valid] = (intensity[valid] - imin) / denominator

    colors = COLORMAP(int_norm)[:, :3]  # RGBA → RGB

    mesh.vertex_colors = o3d.utility.Vector3dVector(colors)

    # -----------------------------
    # 5. SAVE RESULT
    # -----------------------------
    rospy.loginfo(f"Saving textured mesh to: {output_mesh}")
    o3d.io.write_triangle_mesh(output_mesh, mesh)

    rospy.loginfo("✅ Projection successfully completed!")

if __name__ == "__main__":
    main()